### ISSUE TITLE
Cannot find any-observable

### ISSUE THREAD

**Issue by MichaelHirn** [faastjs/faast.js#522] opened 2020-09-17 12:04 UTC
I ran into the issue as mentioned in the title and as it is documented [here](https://faastjs.org/docs/errors#cannot-find-any-observable). I was able to fix it as the documentation suggested, however it is

1. suboptimal, because it requires to move the shared library code into every application library
2. also really weird to me. I don't understand what the underlying issue is, ie how the shared library code causes the error.

Note: The PR that fixed it for me is [here](https://github.com/MichaelHirn/dddf/pull/9) - specifically deleting the `faast.useCase.ts` file that exports a `FaastUseCase` class that abstracts faast implementation for downstream code.

**Comment by acchou** [comment] 2020-09-17 16:01
Basically the issue is that faast cannot be used in the remote module because faast cannot pack itself up. In theory it's possible you might want to invoke a lambda function from within a lambda function, but for now that cannot be done by importing faast into the remote module. Most likely, that's not what you were trying to do in the first place... 

The documentation refers to a case where the remote module and local code both imported a common file, which contained a utility function that used `FaastError` imported from faast itself. In this case, the utility function was only used on the local side (in the remote code, there's no point in checking for a timeout, it's just reported as an error to the caller). But when a faast is called on the remote code, it uses webpack to package the code for execution on lambda. When webpack runs, it finds all the dependencies of the remote code, including faast itself, through the importing of `FaastError`. When webpack tries to pack up faast, it fails because some of the dependencies of faast are not statically determined (for example, webpack itself. So you might say that "faast cannot be used on itself because it depends on webpack, and webpack cannot webpack itself").

The solution was simple: just move the utility function that used `FaastError` into a non-shared file that was only imported on the local side, not the remote module. There's no point in trying to see timeout errors on the remote side, after all. It was just a spurious dependency.

If you could share a little about how you're using faast.js, I'd be happy to give some pointers.

**Comment by MichaelHirn** [comment] 2020-09-17 21:10
Hey @acchou. That makes total sense.

> When webpack tries to pack up faast, it fails because some of the dependencies of faast are not statically determined (for example, webpack itself. So you might say that "faast cannot be used on itself because it depends on webpack, and webpack cannot webpack itself").

Thanks for explaining what the underlying issue is. I presume I may have introduced some spurious dependency somewhere. I will do some digging in the coming days and report back. Thanks a lot already.

**Comment by acchou** [comment] 2020-09-17 22:10
No problem. If you're open to sharing, what's your use case? Have you encountered any issues/limitations with using faast as part of your project?

**Comment by MichaelHirn** [comment] 2020-09-18 10:54
For sure, happy to share. Would be great to get some feedback or "best practices" as well - will leave some open questions/issues at the end.

### Use Case

So the use-case for us is general-purpose, parallel batch computing. And to conclude everything that follows: it is fantastic at that - it's very simple and has a good developer experience. Great job 💯 and a big thank you for that 🙏 

So we are leveraging AWS S3, DynamoDB a lot and there are several use cases for us where we have to touch a large subset of our data and perform some sort of computation on it. Sometimes it is some form of data migration, other times it is an actual business use case that happens infrequently or ad-hoc like some type of reporting or aggregates, etc.

The big draw for us is, that we don't have to spend a lot of time up front hosting (and then managing) a general-purpose computation framework, nor do we have to spend a lot of time planning out all edge cases so that they work in a completely event or real-time based manner. We can start out writing it as a script (that leverages faast) to make it run heavily parallelized so that those scripts finish in a respectable amount of time.

We used a few other tools before, e.g. terraform, serverless, pulumi. Obviously they are more general purpose than just deploying some lambda functions, but we stopped using them for all general-purpose parallel batch computing tasks and now exclusively use faast, because it is a much better developer experience.

### Feedback

I don't think we encountered any 'issues', not even a lot of friction. It mostly centers around how can we make it even easier to leverage faast, so would be great to learn how you think about some of the topics that come below or how other ppl are solving them etc.

1. This is the straight forward one. It has to do with authentication when faast deploys the functions. We have several AWS profiles (e.g. different development environments) and to get them deployed correctly we are using the AWS profile envs, e.g. `AWS_PROFILE=dev_acc AWS_SDK_LOAD_CONFIG=true node path/to/faast-script.js`. However, it would be great to specify the access_key_id and secret_key in the [AWS Options](https://faastjs.org/docs/api/faastjs.awsoptions) which would integrate much better with how we are managing configs for different environments.

2. This one is more complex and is basically about making it even easier to run code remotely. That's the main purpose of our [`FaastUseCase`](https://github.com/MichaelHirn/dddf/blob/v1.9.4/src/useCases/faast/faast.useCase.ts) class that abstracts a lot of the Faast life-cycle steps away. Implementing you create a single `main` class that notably takes an `Rxjs` stream and then invokes a remote function call for each element in that stream. That works great for us. Currently there are two challenges that we're improving one
The first one is the content of this issue - preventing any spurious dependencies; probably easy enough.
The second one is about improving data sharing between host and remote. Specifically serializing config that the remote function has to use to construct classes correctly. We are using inversify.js for anything that does not run remote, but we can't just pass the inversify container because it doesn't serialize. So the thinking is to have a "config inversify" that just passes the serializable config arguments (e.g. serverEndpointURIs, accessKeys, etc.) and not entire classes. But I'm open to hear other ways. The other one is about serializing results from remote back to the host, specifically any errors or relevant statistics. Currently we are using a simple `Result` object `{ value: T, error: Error.stack }` that every function returns. Helps a lot with development speed as you see errors on your console like if it ran locally and without having to consult the AWS logs for everything. But it's just a few util methods atm. Would be curious if there are any libraries you are using to solve those or adjacent problems.

**Comment by acchou** [comment] 2020-09-21 04:20
> ### Use Case
> So the use-case for us is general-purpose, parallel batch computing. And to conclude everything that follows: it is fantastic at that - it's very simple and has a good developer experience. Great job 💯 and a big thank you for that 🙏

That's great to hear, I'm glad you've found it useful.

> So we are leveraging AWS S3, DynamoDB a lot and there are several use cases for us where we have to touch a large subset of our data and perform some sort of computation on it. Sometimes it is some form of data migration, other times it is an actual business use case that happens infrequently or ad-hoc like some type of reporting or aggregates, etc.

If you're comfortable sharing some parameters around these workloads -- it would be interesting to know how many workloads you run per day, how long each workload lasts, and how long the typical function invocation lasts. Even ballpark figures.
 
> We used a few other tools before, e.g. terraform, serverless, pulumi. Obviously they are more general purpose than just deploying some lambda functions, but we stopped using them for all general-purpose parallel batch computing tasks and now exclusively use faast, because it is a much better developer experience.

I've recently scaled up some of my batch jobs and run into various issues that faast now takes care of. I continue to be surprised by how hard it is to get this niche use case right. I'm pretty sure more generic frameworks don't pay attention to these issues...

> 1. This is the straight forward one. It has to do with authentication when faast deploys the functions. We have several AWS profiles (e.g. different development environments) and to get them deployed correctly we are using the AWS profile envs, e.g. `AWS_PROFILE=dev_acc AWS_SDK_LOAD_CONFIG=true node path/to/faast-script.js`. However, it would be great to specify the access_key_id and secret_key in the [AWS Options](https://faastjs.org/docs/api/faastjs.awsoptions) which would integrate much better with how we are managing configs for different environments.

Good idea. I added #527 to track this.

>    The second one is about improving data sharing between host and remote. Specifically serializing config that the remote function has to use to construct classes correctly. We are using inversify.js for anything that does not run remote, but we can't just pass the inversify container because it doesn't serialize. So the thinking is to have a "config inversify" that just passes the serializable config arguments (e.g. serverEndpointURIs, accessKeys, etc.) and not entire classes. But I'm open to hear other ways. The other one is about serializing results from remote back to the host, specifically any errors or relevant statistics. Currently we are using a simple `Result` object `{ value: T, error: Error.stack }` that every function returns. Helps a lot with development speed as you see errors on your console like if it ran locally and without having to consult the AWS logs for everything. But it's just a few util methods atm. Would be curious if there are any libraries you are using to solve those or adjacent problems.

There are a few tools and patterns, which, taken together, should solve most of these use cases with faast.js without the addition of a wrapper class:

- Prefer a functional programming style without classes. Typically in this style you'll define interfaces for the argument and return types. By using data-centric interfaces with faast, you'll have accurate types for arguments and return values when you call remote functions.

- Functional programming often uses higher order functions and functions don't serialize as arguments. What I've often found is that you can still write your remote functions as higher order, but then make sure the function arguments are also defined on the remote side, and make a wrapper function that invokes the higher-order function. This gives you most of the benefits of higher order programming without needing to actually serialize functions to make remote calls.

- Errors thrown on the remote side are propagated to local and reconstituted and rethrown there. This should make it easy to use the usual try-catch patterns used in async functions to handle errors. Note that this only works for `Error` and not other error types, because faast cannot guarantee that it can reconstitute such errors. 

- This is under-documented, but it's possible to define your remote functions as async generators. The cool thing here is each yield on the remote function is queued immediately and received asynchronously (without pausing for the promise resolution on the local side - it's not two way communication). This means you can send partial results, statistics, and other messages "as you go" instead of waiting for the lambda function to complete once. The programming model is nearly transparent as well: the local function is presented as an async generator and you can use for...await as you'd expect. Errors are even propagated to the promises. It may be possible to wrap faast async generators inside RxJS streams--but I haven't tried.

Not sure if these address your use case but I thought I'd share what's worked for me.

**Comment by acchou** [comment] 2020-09-21 15:57
BTW you can now add credentials to faastAws as part of AwsOptions, see #527.

**Comment by acchou** [comment] 2020-09-22 18:03
Closing this issue; happy to continue the larger conversation by email or slack.

**Closed by acchou** 2020-09-22 18:03 UTC

**Comment by MichaelHirn** [comment] 2020-09-26 12:25
Hey @acchou, wanted to follow up here as I didn't get much time during the week.

Big thanks for the quick feature merge and your comments. Will update to the latest version next week and use it - very excited retire the env vars 👍 

Would be happy to continue the convo on slack (link in the readme is broken?) and give some more details on our use case.

**Comment by acchou** [comment] 2020-09-27 02:54
Argh, I didn't realize that Slack invite links expire. Since there was little activity there (now I know why!), I've decided to switch to Discord. Check out the new link to the discussion forum and let's chat in Discord.

**Comment by acchou** [comment] 2020-09-27 02:54
Here's an invite link btw: https://discord.gg/F3aqjb3
